[google]
api_key = "AIzaSyBZ1oNBc74mCBB3Mc161f4CVHWorxV5iaA"

[passcodes]
"admin" = { code = "malaostia", max_pages = 3 }
"IgnacioBarrios" = { code = "nachito", max_pages = 3 }
"Pepe querido" = { code = "josecristo", max_pages = 3 }
"Rob" = { code = "canada", max_pages = 3 }
